import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { BsSearch } from "react-icons/bs";
import { useState } from 'react';
import axios from 'axios';
import bg from '../public/bg.jpg';
import Weather from '@/components/Weather';
import Spinner from '@/components/Spinner';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((res) => {
      setWeather(res.data)
    })
    setCity('')
    setLoading(false)
  }
  if (loading) {
   return <Spinner /> 
  }
  return (
    <>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'></div>
      <Image
        src={bg}
        alt="bakcground"
        fill
        className='object-cover'
      />
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
        <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
            <input 
              onChange={(e)=>setCity(e.target.value)}
              value={city}
              type="text" 
              placeholder='Search city' 
              className='w-full bg-transparent border-none text-white text-2xl focus:outline-none' />
          <button>
            <BsSearch size={25} />
          </button>
        </form>
      </div>
      {
        weather.main && <Weather data={weather} />
      }
    </>
  )
}
